variable "region" {}
variable "project_name" {}
variable "vpc_cider" {}
variable "public_subnet_az1_cider" {}
variable "public_subnet_az2_cider" {}
variable "private_app_subnet_az1_cider" {}
variable "private_app_subnet_az2_cider" {}
variable "private_data_subnet_az1_cider" {}
variable "private_data_subnet_az2_cider" {}